In [1]:
import h5py
import numpy as np
import pandas as pd

In [2]:
hou = h5py.File('01_Sample_Data.h5','r')
feat = hou['feat']
feat = np.array(feat)
lab = hou['lab']
lab = np.array(lab)

print(feat.shape)
print(lab.shape)


(50, 60660)
(50,)


In [3]:
feat.max()

45378.2555

In [4]:
feat_modified = np.where(feat > 5000, 1000 + feat / 100,
                                   np.where(feat > 500, 500 + feat / 10, feat))

In [5]:
feat_modified.max()

1453.782555

In [6]:
std = np.std(feat,axis=0)

In [7]:
x = std[std > 1]
x.shape

(16397,)

In [8]:
import pandas as pd
patho = r'01_genenametq.tsv'
data0 = pd.read_table(patho,header=None,delim_whitespace=True)#encoding='gb2312',index_col=0
print(data0.shape)
names1 = data0[0]
names2 = data0[1]
names1 = names1.values.tolist()
names2 = names2.values.tolist()
print(len(names1))

(60660, 9)
60660


In [9]:
import time
from tqdm import tqdm
from tqdm._tqdm import trange

C:\Users\38152\.conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.std.*` instead of `tqdm._tqdm.*`
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
blist1 = []
qlist1 = []
blist2 = []
qlist2 = []
for i in tqdm(range(len(names1))):
    time.sleep(0.01)
    a = std[i]
    if a <= 1:
        qlist1.append(i)
        qlist2.append(i)
    else:
        blist1.append(i)
        blist2.append(i)
        #feature = np.delete(feature,i,1)
        #del names[i]
    #print(names[i])

100%|██████████| 60660/60660 [17:18<00:00, 58.40it/s]


In [11]:
blist1 = np.array(blist1)
qlist1 = np.array(qlist1)
blist2 = np.array(blist2)
qlist2 = np.array(qlist2)

In [12]:
blist1

array([    0,     1,     2, ..., 60565, 60612, 60656])

In [13]:
blist2

array([    0,     1,     2, ..., 60565, 60612, 60656])

In [14]:
qlist1

array([    3,    17,    18, ..., 60657, 60658, 60659])

In [15]:
qlist2

array([    3,    17,    18, ..., 60657, 60658, 60659])

In [16]:
blist1.shape

(16397,)

In [17]:
featqc = np.delete(feat_modified,[qlist1],1)

In [18]:
featqc.shape

(50, 16397)

In [19]:
nam1 = []
nam2 = []
for i in range(len(blist1)):
    nam1.append(names1[blist1[i]])
    nam2.append(names2[blist2[i]])

In [20]:
import h5py 
f = h5py.File('prefeat_cf.h5', 'w')
f.create_dataset('feat', data=featqc)
f.create_dataset('lab', data=lab)
f.close()

In [21]:
nam1

['ENSG00000000003.15',
 'ENSG00000000005.6',
 'ENSG00000000419.13',
 'ENSG00000000460.17',
 'ENSG00000000938.13',
 'ENSG00000000971.16',
 'ENSG00000001036.14',
 'ENSG00000001084.13',
 'ENSG00000001167.14',
 'ENSG00000001460.18',
 'ENSG00000001461.17',
 'ENSG00000001497.18',
 'ENSG00000001561.7',
 'ENSG00000001617.12',
 'ENSG00000001626.16',
 'ENSG00000001629.10',
 'ENSG00000002016.18',
 'ENSG00000002330.14',
 'ENSG00000002549.12',
 'ENSG00000002586.20',
 'ENSG00000002587.10',
 'ENSG00000002726.21',
 'ENSG00000002745.13',
 'ENSG00000002834.18',
 'ENSG00000002919.15',
 'ENSG00000002933.9',
 'ENSG00000003056.8',
 'ENSG00000003096.14',
 'ENSG00000003137.8',
 'ENSG00000003147.19',
 'ENSG00000003249.15',
 'ENSG00000003393.15',
 'ENSG00000003400.15',
 'ENSG00000003402.20',
 'ENSG00000003436.16',
 'ENSG00000003509.16',
 'ENSG00000003756.17',
 'ENSG00000003989.18',
 'ENSG00000004059.11',
 'ENSG00000004142.12',
 'ENSG00000004399.13',
 'ENSG00000004455.17',
 'ENSG00000004468.13',
 'ENSG0000000447

In [22]:
import re
file3 = open('prefeat_cf_name1.txt', 'w')
file4 = open('prefeat_cf_name2.txt', 'w')
for i in range(len(nam1)):
    s = (re.sub(r"['{ },]*", '', str(nam1[i])) + '\n').replace(':', ',')
    file3.write(s)
    ss = (re.sub(r"['{ },]*", '', str(nam2[i])) + '\n').replace(':', ',')
    file4.write(ss)
file3.close()
file4.close()