In [31]:
import h5py
import numpy as np
import pandas as pd

In [32]:
data = h5py.File('03_newname_cf.h5','r')
feat = data['feat']
feat_x = np.array(feat)
print(feat_x.shape)
lab = data['lab']
feat_y = np.array(lab)
print(feat_y.shape)

(11074, 1089)
(11074,)


In [33]:
patho = r'03_newname_cf.txt'
data0 = pd.read_table(patho,header=None,delim_whitespace=True)#encoding='gb2312',index_col=0
print(data0.shape)
names = data0[0]
names = names.values.tolist()
print(len(names))

(1089, 1)
1089


In [34]:
names

['5_8S_rRNA',
 '5_8S_rRNA',
 'A2M',
 'A2ML1',
 'A4GALT',
 'AADAC',
 'AAGAB',
 'AAMP',
 'AAR2',
 'AARD',
 'AARS1',
 'AATF',
 'ABAT',
 'ABCA1',
 'ABCA2',
 'ABCA3',
 'ABCB1',
 'ABCC1',
 'ABCC11',
 'ABCC2',
 'ABCC3',
 'ABCC4',
 'ABCC5',
 'ABCD1',
 'ABCD3',
 'ABCE1',
 'ABCF1',
 'ABCF3',
 'ABCG1',
 'ABCG2',
 'ABHD10',
 'ABHD11',
 'ABHD11-AS1',
 'ABHD12',
 'ABHD14B',
 'ABHD17C',
 'ABHD2',
 'ABHD3',
 'ABHD4',
 'ABHD8',
 'ABI1',
 'ABI3',
 'ABI3BP',
 'ABL1',
 'ABLIM1',
 'ABLIM3',
 'ABO',
 'ABR',
 'ABRACL',
 'ABT1',
 'AC002064.2',
 'AC004453.1',
 'AC004687.1',
 'AC005180.2',
 'AC005336.1',
 'AC005392.2',
 'AC005828.4',
 'AC005912.1',
 'AC006205.2',
 'AC007547.2',
 'AC007906.2',
 'AC007991.2',
 'AC008038.1',
 'AC008663.1',
 'AC008736.1',
 'AC008753.2',
 'AC008760.2',
 'AC009078.2',
 'AC009283.1',
 'AC010343.1',
 'AC010503.4',
 'AC010677.1',
 'AC010970.1',
 'AC011228.2',
 'AC011447.7',
 'AC011487.2',
 'AC012065.2',
 'AC012618.1',
 'AC013457.1',
 'AC015722.2',
 'AC015910.1',
 'AC015922.2',
 'AC01592

In [35]:
feat_x.shape

(11074, 1089)

In [36]:
feat_y.shape

(11074,)

In [37]:
std = np.mean(feat_x,axis=0)

In [38]:
std.shape

(1089,)

In [39]:
ran = np.arange(1089)

In [40]:
ran

array([   0,    1,    2, ..., 1086, 1087, 1088])

In [41]:
feat = np.vstack((feat_x,ran,std))
print(feat.shape)

(11076, 1089)


In [42]:
data = feat.T[np.lexsort(feat)].T

In [43]:
data.shape

(11076, 1089)

In [51]:
data[len(data)-2]

array([ 90.,  59., 150., ..., 814., 220., 218.])

In [52]:
px = data[len(data)-2]

In [54]:
px

array([ 90.,  59., 150., ..., 814., 220., 218.])

In [55]:
len(ran)

1089

In [56]:
namen=[]

In [57]:
for i in range(len(ran)):
    for j in range(len(ran)):
        if px[i]==ran[j]:
            namen.append(names[j])

In [58]:
len(namen)

1089

In [59]:
namen

['AC021713.1',
 'AC007547.2',
 'AC113410.2',
 'AC022081.1',
 'AF241725.1',
 'AC011228.2',
 'AMELX',
 'AL713998.1',
 'ACTG1P22',
 'AC082651.3',
 'BX322234.2',
 'AMBN',
 'BPIFB4',
 'AC013457.1',
 'AC105914.2',
 'AC009078.2',
 'AL121938.1',
 'AP005273.2',
 'AL589787.2',
 'AC108752.1',
 'AC104823.1',
 'AF178030.1',
 'CA6',
 'AC006205.2',
 'AC128657.1',
 'AC093838.1',
 'AC090994.1',
 'AC246787.2',
 'AC026355.3',
 'AC008753.2',
 'AC064802.1',
 'AGTR2',
 'AC099789.1',
 'AP000432.1',
 'AC244035.3',
 'AGRP',
 'AC120498.2',
 'AC083967.1',
 'ART3',
 'ALAS2',
 'AC011487.2',
 'AL035425.3',
 'AC079466.1',
 'AL356311.1',
 'AC002064.2',
 'AC129507.4',
 'AC073869.6',
 'AC005828.4',
 'C19orf85',
 'AC245100.3',
 'BPIFA2',
 'AHSP',
 'AC015722.2',
 'ALPI',
 'C3P1',
 'AC104051.2',
 'AC112206.3',
 'ATOH1',
 'AC073140.1',
 'AC125603.1',
 '5_8S_rRNA',
 '5_8S_rRNA',
 'AC125603.2',
 'AL355922.1',
 'C11orf53',
 'AC021744.1',
 'AKR1D1',
 'AP005432.2',
 'AQP6',
 'AL109615.3',
 'ADCYAP1',
 'C11orf86',
 'AL078582.2',

In [60]:
import re
file32 = open('d:/h5/newnameknn_cf_px.txt', 'w')

for i in range(len(namen)):
    s = (re.sub(r"['{ },]*", '', str(namen[i])) + '\n').replace(':', ',')
    file32.write(s)
file32.close()

In [61]:
myarray = [[j for j in range(33)] for i in range(33)] 

In [62]:
N=33

In [63]:
myarray = np.zeros((N, N))
df = [[j for j in range(33)] for i in range(33)] 
x, y = 0, N - 1
res = myarray[x][y] = 1

while res < N * N:
        while x + 1 < N and not myarray[x + 1][y]:
        res += 1
        x += 1
        myarray[x][y] = res
        df[x][y] = namen[min(res - 1, 1088)]

        while y - 1 >= 0 and not myarray[x][y - 1]:
        res += 1
        y -= 1
        myarray[x][y] = res
        df[x][y] = namen[min(res - 1, 1088)]

        while x - 1 >= 0 and not myarray[x - 1][y]:
        res += 1
        x -= 1
        myarray[x][y] = res
        df[x][y] = namen[min(res - 1, 1088)]

    n    while y + 1 < N and not myarray[x][y + 1]:
        res += 1
        y += 1
        myarray[x][y] = res
        df[x][y] = namen[min(res - 1, 1088)]

In [64]:
df

[['AC005180.2',
  'C1QTNF4',
  'AC015910.1',
  'AP003774.2',
  'AL139099.3',
  'AC107385.2',
  'ADAMTS8',
  'B4GALNT1',
  'APOBEC2',
  'ACTL8',
  'AL021068.1',
  'AC111000.2',
  'AKR1B15',
  'AC105460.1',
  'ATP6V1G3',
  'AL354766.2',
  'C6orf58',
  'AL079338.1',
  'AC084375.1',
  'BTBD16',
  'C1QL4',
  'ANKRD30A',
  'ARMH1',
  'AMY2A',
  'ALPP',
  'AC244102.3',
  'ALDH1A2',
  'ASIC4',
  'AC103591.3',
  'AC012618.1',
  'ATP4B',
  'B3GNT6',
  32],
 ['AL606500.1',
  'ASPRV1',
  'AC025580.1',
  'C1QTNF3',
  'ADAM23',
  'ADH6',
  'ARHGEF4',
  'BEND5',
  'ARL14',
  'AC245297.1',
  'AC103702.2',
  'ASIC1',
  'ATP6V0D2',
  'AL122020.1',
  'C6orf15',
  'AL162413.1',
  'ACE',
  'C2orf88',
  'ATP13A4',
  'AL157931.1',
  'CA4',
  'ACSM2B',
  'ANGPT2',
  'AL365181.3',
  'CACNA1H',
  'ATG16L2',
  'C5orf38',
  'C9orf116',
  'ASTN2',
  'C6',
  'AFM',
  'BTBD17',
  'AC007547.2'],
 ['ANKRD2',
  'ANXA8',
  'C9',
  'ACTC1',
  'AL591846.1',
  'AXIN2',
  'APOA5',
  'AC093297.2',
  'AMOT',
  'BPIFB2',
  'AP

In [65]:
import pandas as pd

In [66]:
dff = pd.DataFrame(df)

In [67]:
dff.to_csv('newname_cf_px.csv',header=False,index=False)